### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by jonathonsim** [omerxx/ecscale#5]
Nice looking solution.  Would you consider adding an open source license (my preference would be an MIT license, but it's your choice obviously) so it's clear to people they can use this code?

Good docs here from github here, only takes a second:
https://help.github.com/articles/adding-a-license-to-a-repository/

Happy to submit a PR but it's a bit presumptuous for me to select an open source license for you!

**Comment by omerxx** [comment]
@jonathonsim Sorry for the delay, you are right.
I'm adding a license right now.
